version: '3.8'

services:
  api:
    build: .
    container_name: redarbor-api
    ports:
      - "7262:8080"
    environment:
      - ConnectionStrings__RedarborConnection=Server=sqlserver;Database=redarbor;User Id=sa;Password=P4ssw0rd*;TrustServerCertificate=True;Encrypt=False
      - Jwt__Key=my_super_secret_key_for_R3d4rb0rT3$t*
      - Jwt__Issuer=RedArborAPI
      - Jwt__Audience=RedArborClient
      - Jwt__ExpiryMinutes=60
    depends_on:
      - sqlserver
    networks:
      - redarbor-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: redarbor-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P4ssw0rd*
      - MSSQL_PID=Developer
    ports:
      - "1434:1433"
    networks:
      - redarbor-network

networks:
  redarbor-network:
    driver: bridge